#!/bin/bash

DIR=$(cd "$(dirname "$0")"; cd ../../../; pwd)
INST="/Applications/iNZightVIT"

## check directory - if not /Applications/iNZightVIT - move
if [ "$DIR" != "$INST" ]; then
  CONT="$(osascript -e 'display dialog "You need to move the iNZightVIT folder to Applications before it will run.\n\nWould you like to do this now?" with title "Move iNZightVIT to Applications" buttons {"Yes", "No"} default button 1')"
  echo $CONT
  if [ "$CONT" = "button returned:Yes" ]; then
    mv "$DIR" "$INST"
    open -a /Applications/iNZightVIT/iNZight.app
  fi
  exit 0
fi

defaults write org.R-project.R NSAppSleepDisabled -bool YES
export R_DIR="/Applications/iNZightVIT/iNZight.app/Contents/MacOS/"
open -a R $R_DIR
